// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhgeqtzehiubwaqyvydc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoZ2VxdHplaGl1YndhcXl2eWRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MzgzMTMsImV4cCI6MjA3MTAxNDMxM30.O4qwgZWtBnri716SNr9r9nARg8s2cZD4RvkTkLIErNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});